comment out terraform

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -58,7 +58,7 @@ jobs:
         run: |
           cat lambda/determine_replacements_caselaw/requirements.txt
           # docker pull hello-world
-          cd lambda/determine_replacements_caselaw4406
+          cd lambda/determine_replacements_caselaw0879
           sudo AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 30071420.dkr.ecr.eu-west-2.amazonaws.com
           # aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 087925987720.dkr.ecr.eu-west-2.amazonaws.com/tna-s3-tna-ecr-repository-dev:latest
           echo "logged in"
@@ -83,26 +83,26 @@ jobs:
           docker push 087925987720.dkr.ecr.eu-west-2.amazonaws.com/tna-s3-tna-ecr-repository-legislation-dev:latest
 
 
-  terraform:
-    name: "Terraform"
-    runs-on: ubuntu-latest
+#  terraform:
+  #  name: "Terraform"
+  #  runs-on: ubuntu-latest
     # container:
     #   image: hashicorp/terraform:light
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
+  #  steps:
+  #    - name: Checkout
+  #      uses: actions/checkout@v3
 
-      - name: Copy Python into Lambda
-        id: move
-        run: |
-          mkdir lambda/extract_judgement_contents/caselaw_extraction
-          cp -r caselaw_extraction/*.py lambda/extract_judgement_contents/caselaw_extraction/
+  #    - name: Copy Python into Lambda
+  #      id: move
+  #      run: |
+  #        mkdir lambda/extract_judgement_contents/caselaw_extraction
+  #        cp -r caselaw_extraction/*.py lambda/extract_judgement_contents/caselaw_extraction/
 
-          mkdir lambda/extract_judgement_contents/utils
-          cp -r utils/*.py lambda/extract_judgement_contents/utils/
+  #        mkdir lambda/extract_judgement_contents/utils
+  #        cp -r utils/*.py lambda/extract_judgement_contents/utils/
 
-          mkdir -p lambda/make_replacements/replacer
-          cp -r replacer/*.py lambda/make_replacements/replacer/
+  #        mkdir -p lambda/make_replacements/replacer
+  #        cp -r replacer/*.py lambda/make_replacements/replacer/
 
       # - name: Set up Docker Buildx
       #   uses: docker/setup-buildx-action@v1
@@ -112,27 +112,27 @@ jobs:
 #         docker push ${aws_ecr_repository.main.repository_url}:${var.container_image_tag}
 #  
 
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v1
-        with:
+  #    - name: Setup Terraform
+  #      uses: hashicorp/setup-terraform@v1
+  #      with:
           # terraform_version: 0.13.0:
-          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
+  #        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
 
       # - name: Terraform Format
       #   id: fmt
       #   run: terraform fmt -check -diff
 
-      - name: Terraform Init
-        id: init
-        run: terraform init -upgrade
+  #    - name: Terraform Init
+  #      id: init
+  #      run: terraform init -upgrade
       
-      - name: Terraform Validate
-        id: validate
-        run: terraform validate -no-color
+  #    - name: Terraform Validate
+  #      id: validate
+  #      run: terraform validate -no-color
 
-      - uses: actions/setup-python@v3
-        with:
-          python-version: '3.8'
+  #    - uses: actions/setup-python@v3
+  #      with:
+  #        python-version: '3.8'
       # - name: Install dependencies
       #   run: |
       #     python -m pip install --upgrade pip
@@ -148,48 +148,48 @@ jobs:
       #   run: |
       #     pytest
 
-      - name: Terraform Plan
-        id: plan
-        if: github.event_name == 'pull_request'
-        run: terraform plan -no-color
-        continue-on-error: true
+  #    - name: Terraform Plan
+  #      id: plan
+  #      if: github.event_name == 'pull_request'
+  #      run: terraform plan -no-color
+  #      continue-on-error: true
 
-      - uses: actions/github-script@0.9.0
-        if: github.event_name == 'pull_request'
-        env:
-          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          script: |
-            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
-            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
-            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
-            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
+  #    - uses: actions/github-script@0.9.0
+  #      if: github.event_name == 'pull_request'
+  #      env:
+  #        PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
+  #      with:
+  #        github-token: ${{ secrets.GITHUB_TOKEN }}
+  #        script: |
+  #          const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
+  #          #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
+  #          #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
+  #          #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
 
-            <details><summary>Show Plan</summary>
+  #          <details><summary>Show Plan</summary>
 
-            \`\`\`\n
-            ${process.env.PLAN}
-            \`\`\`
+  #          \`\`\`\n
+  #          ${process.env.PLAN}
+  #          \`\`\`
 
-            </details>
+  #          </details>
 
-            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
+  #          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
 
-            github.issues.createComment({
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: output
-            })
+  #          github.issues.createComment({
+  #            issue_number: context.issue.number,
+  #            owner: context.repo.owner,
+  #            repo: context.repo.repo,
+  #            body: output
+  #          })
 
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+  #    - name: Terraform Plan Status
+  #      if: steps.plan.outcome == 'failure'
+  #      run: exit 1
 
-      - name: Terraform Apply
-        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-        run: terraform apply -auto-approve
+  #    - name: Terraform Apply
+  #      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+  #      run: terraform apply -auto-approve
   # test:
   #   runs-on: ubuntu-latest
   #   strategy:
